# http://docs.ansible.com/ansible/intro_windows.html#windows-how-does-it-work

ansible_user: vagrant
ansible_password: vagrant
ansible_connection: psrp
ansible_port: 55986
ansible_psrp_transport: basic
ansible_psrp_cert_validation: ignore